from get_and_process_data_massela.webscraping import ConfigSelenium
import time
# Generated by Selenium IDE

import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.common.keys import Keys

sleep = 5


class AppSisRun(ConfigSelenium):

    def __init__(self):
        super().__init__()
        self.url_home = 'https://appsisrun.com.br/sisrun/login.xhtml'
        self.url_detail = 'https://appsisrun.com.br/sisrun/pages/consulta/analiseTreinos/listaAnaliseTreinos.xhtml'

    def navigate_page_login(self):
        self.driver.get(self.url_home)
        self.driver.maximize_window()
        time.sleep(sleep)

    def login(self):
        self.driver.find_element(By.ID, "frmLogin:email").click()
        self.driver.find_element(By.ID, "frmLogin:email").send_keys(
            "masellaassessoria@gmail.com")
        time.sleep(sleep)
        self.driver.find_element(By.ID, "frmLogin:senha").click()
        self.driver.find_element(By.ID, "frmLogin:senha").send_keys("246810")
        time.sleep(sleep)
        self.driver.find_element(By.XPATH,
                                 "//span[contains(.,\'Entrar\')]").click()

    def get_list_students(self):
        self.driver.find_element(By.CSS_SELECTOR,
                                 "#frmLogin\\3Aj_idt34 > .ui-button-text").click()
        time.sleep(sleep)
        self.driver.find_element(By.CSS_SELECTOR, ".fa-users").click()
        self.driver.find_element(By.CSS_SELECTOR,
                                 "#frmConsulta\\3AtabCadastro\\3Aj_idt401 > .ui-button-text").click()
        time.sleep(sleep)

    def navitegate_page_detail(self):

        self.driver.get(self.url_detail)
        time.sleep(3)


    def teste(self, list_students):

        for student in list_students:
            student = student.strip()
            print(f'Baixando -- {student}')
            self.driver.find_element(By.ID,
                                     "frmConsulta:comboAluno_input").click()
            time.sleep(1)
            self.driver.find_element(By.ID,
                                     "frmConsulta:comboAluno_input").clear()
            self.driver.find_element(By.ID,
                                     "frmConsulta:comboAluno_input").click()
            self.driver.find_element(By.ID,
                                     "frmConsulta:comboAluno_input").send_keys(
                student)
            time.sleep(sleep)
            self.driver.find_element(By.ID, "frmConsulta:console_label").click()
            time.sleep(sleep)
            self.driver.find_element(By.ID, "frmConsulta:console_2").click()
            time.sleep(sleep)

            self.driver.find_element(By.ID,
                                     "frmConsulta:filtroDataInicial_input").click()
            time.sleep(2)
            self.driver.find_element(By.ID,
                                     "frmConsulta:filtroDataInicial_input").send_keys(
                "01/09/2022")
            time.sleep(sleep)
            self.driver.find_element(By.ID,
                                     "frmConsulta:filtroDataFinal_input").click()
            time.sleep(2)
            self.driver.find_element(By.ID,
                                     "frmConsulta:filtroDataFinal_input").send_keys(
                "09/10/2022")
            time.sleep(sleep)

            self.driver.find_element(By.XPATH,
                                     "//button[@id=\'frmConsulta:botaoConsultar\']/span[2]").click()
            # self.driver.find_element(By.CSS_SELECTOR,
            #                          "#frmConsulta\\3A botaoConsultar > .ui-button-text").click()
            time.sleep(10)

            html = self.driver.find_element_by_tag_name('html')
            html.send_keys(Keys.END)
            self.driver.find_element(By.ID,
                                     "frmConsulta:viewGraficos:tablePlanilha:j_idt368").click()
            html.send_keys(Keys.HOME)
            time.sleep(10)
